/=../../

all = blkhwid findblk kmount switchroot reboot

include ../rules.mk
include $/config.mk

blkhwid: blkhwid.o
findblk: findblk.o
kmount: kmount.o
switchroot: switchroot.o
reboot: reboot.o

-include *.d
