.TH devinit 8
'''
.SH NAME
\fBdevinit\fR \- initrd pid 1 and module autoloader
'''
.SH SYNOPSIS
\fBdevinit\fR
'''
.SH DESCRIPTION
(TODO)
'''
.SH FILES
.IP "\fB/etc/modpipe\fR" 4
This script should start \fBmodprobe\fR(8) in pipe mode (\fB-p\fR).
.IP "\fB/etc/setup\fR" 4
The payload script to run, see \fBfindblk\fR(8).
.IP "\fB/etc/success\fR" 4
Next stage script in case \fBsetup\fR succeeded.
.IP "\fB/etc/failure\fR" 4
Shutdown script in case something fails.
