.TH dmesg 8
'''
.SH NAME
\fBdmesg\fR \- kernel ring buffer tool
'''
.SH SYNOPSIS
.IP "\fBdmesg\fR [\fB-c\fR]" 4
Dump contents of the ring buffer.
.IP "\fBdmesg\fR \fB-n\fR \fIlevel\fR" 4
Set kernel log level.
'''
.SH DESCRIPTION
Kernel log messages (the output of printk()) are kept in a ring buffer.
Current contents of the ring buffer can be examined non-destructively
using \fBdmesg\fR.
.P
The second form sets the kernel log level. Only messages with priority
less that \fIlevel\fR will be printed to the system console. The ring
buffer will still get all the messages regardless of their priority value.
'''
.SH OPTIONS
.IP "\fB-c\fR" 4
Clear the buffer after printing its contents.
'''
.SH SEE ALSO
\fBklogctl\fR(2), \fBlogcat\fR(1), \fBsysklogd\fR(8)
