.TH passblk 8
'''
.SH NAME
\fBpassblk\fR \- passphrase prompt for encrypted block devices
'''
.SH USAGE
This tools should only be used from initrd.
.P
\fBpassblk\fR \fIkeyfile.bin\fR \fIroot\fR \fIhome\fR ...
.P
Ask passphrase to unlock \fIkeyfile.bin\fR, then use the keys there
to set up encryption layer for \fB/dev/mapper/\fIroot\fR and
\fB/dev/mapper/\fIboot\fR respectively.
.P
In case the keys are not used in order, key index can be specified explicitly:
.P
\fBpassblk\fR \fIkeyfile.bin\fR \fI1\fB:\fIroot\fR \fI3\fB:\fIvar\fR ...
.P
Key are indexed starting from 1.
'''
.SH NOTES
The encryption algorithm is always XTS-AES-128, with 256-bit keys.
'''
.SH SEE ALSO
\fBfindblk\fR(8), \fBdektool\fR(8).
