.TH svchub 8
'''
.SH NAME
\fBsvchub\fR \- top-level process supervisor
'''
.SH DESCRIPTION
\fBsvchub\fR runs as PID 1 for most of the system's uptime, spawning
and monitoring a set system services.
'''
.SH USAGE
Upon startup, \fBsvchub\fR spawns \fB/etc/boot/startup\fR and waits
for it to start start some services (by invoking \fBsvcctl start\fR)
and everything that needs to be running in the system. After \fBstartup\fR
finishes, \fBsvchub\fR keeps monitoring the spawned services.
.P
If commanded or signalled to stop, \fBsvchub\fR stops all the services
it supervises and attempts to halt the system by running one of the
shutdown scripts.
'''
.SH FILES
.IP "/etc/boot/startup" 4
System startup script.
.IP "/run/svchub" 4
Control socket.
.IP "/etc/init/\fIname\fR" 4
Service startup scripts (\fBsvcctl start \fIname\fR).
.IP "/etc/boot/shutdown" 4
System shutdown (svcctl reboot, svcctl poweroff etc).
.IP "/etc/boot/failure" 4
Unexpected (non-commanded) shutdown.
.P
The shutdown scripts should in most cases just invoke \fBreboot\fR(1).
'''
.SH SEE ALSO
\fBsvcctl\fR(1), \fBreboot\fR(1), \fBmsh\fR(1).
