.TH blkid 8
'''
.SH NAME
\fBblkid\fR \- show possible persistent identifiers for a block device
'''
.SH SYNOPSIS
\fBblkid\fR \fIsdb\fR
.br
serial FJ68N557021713D91
.br
\fBblkid\fR \fImmcblk0\fR
.br
cid 01203432023487234987234
'''
.SH DESCRIPTION
This tool should help choosing entries for \fBblktab\fR(5).
'''
.SH SEE ALSO
\fBblktab\fR(5), \fBfindblk\fR(8).
