.TH blktab 5
'''
.SH NAME
/etc/blktab \- list of partitions to mount at boot
'''
.SH DESCRIPTION
The purpose of this file is to provide a map between potentially volatile
kernel names for block devices and the identifiably physical devices the
system depends on to allow reliably mounting them during the boot.
.P
The format of the file is quite simple:
.P
.nf
	# Each device is identified using one of its persistent
	# properties, in this case the serial number from VPD Pg.80
	\fBserial\fR \fIFJ68N557021713D91\fR
	# Then partitions of this device are given labels (names)
	# they will be known as while the system is running
	\fBpart\fR \fI1\fR \fIboot\fR
	\fBpart\fR \fI2\fR \fIroot\fR
	# Encrypted partitions need key index and optionally fs type
	\fBpart\fR \fI3\fR \fIhome\fR \fI1\fR \fIext4\fR

	# Similar sections for other devices may follow
.fi
.P
Running \fBpassblk\fR(8) or \fBfindblk\fR(8) on such a file would result
in a set of symlinks poiting to current kernel names of the partitions
that have been identified:
.P
.nf
	/dev/mapper/\fIboot\fR -> /dev/sdb1
	/dev/mapper/\fIroot\fR -> /dev/sdb2
	/dev/mapper/\fIhome\fR -> /dev/dm-1
.fi
.P
In this example /dev/sdb happens to be the block device with serial
number \fIFJ68N557021713D91\fR, and /dev/dm-1 is a dm-crypt device
created for the encrypted sdb3 partition.
'''
.SH KEYWORDS
The following features may be used to identify devices:
.IP "\fBserial\fR \fIABCD....\fR" 4
Matches the data in /sys/block/\fIsdb\fR/device/vpd_pg80. The leading
four bytes are skipped, leading and trailing spaces are trimmed.
.IP "\fBcid\fR \fI0123...\fR" 4
Matches SD card ID found in /sys/block/\fImmcblk0\fR/device/cid,
typically a long decimal number.
.IP "\fBmbr\fR \fI0011FFEE\fR" 4
Matches MBR signature; \fBfdisk\fR(1) reports it as "Disk identifier".
This is always a 4-byte hex number.
.IP "\fBgpt\fR \fI00112233-4455-6789-ABCD-0123456789AB\fR" 4
Matches GPT GUID; \fBgdisk\fR(1) reports it as "Disk identifier (GUID)".
Always a 16-byte hex value, typically formatted as shown.
.P
Partition entries rely on the kernel numbering, no additional identification
is performed.
.IP "\fBpart\fR \fIN\fR \fIlabel\fR [\fIK\fR \fIfs\fR]" 4
If the base device is \fIsdb\fR, this assigns \fIlabel\fR to \fIsdbN\fR.
Most cases should have numeric \fIN\fR although some flash devices may require
a string here like \fIboot0\fR. The common case of \fImmcblk0p1\fR needs
just \fI1\fR.
.IP "\fBwhole\fR \fIlabel\fR [\fIK\fR \fIfs\fR]" 4
Label the whole device.
'''
.SH SEE ALSO
\fBfindblk\fR(8), \fBpassblk\fR(8), \fBblkid\fR(8).
