.TH deitool 8
'''
.SH NAME
\fBdeitool\fR \- encrypted disk image tool
'''
.SH SYNOPSIS
\fBdeitool\fR \fB-\fR[\fBde\fR] \fIsource\fR \fIoutput\fR \fIkeyfile\fR [\fIkidx\fR]
'''
.SH OPTIONS
.IP "\fB-d\fR" 4
Decrypt encrypted image \fIsource\fR into \fIoutput\fR.
.IP "\fB-e\fR" 4
Encrypt plaintext image \fIsource\fR into \fIoutput\fR.
'''
.SH SEE ALSO
\fBdektool\fR(8)
