.TH deitool 8
'''
.SH NAME
\fBdeitool\fR \- disk image encryption tool
'''
.SH SYNOPSIS
\fBdeitool\fR \fR[\fB-ds\fR] \fIsource\fR \fIoutput\fR \fIkeyfile\fR [\fIkidx\fR]
'''
.SH DESCRIPTION
This tool applies the same algorithm (XTS-AES-128) as \fBpassblk\fR(8)
using key \fIkidx\fR from \fIkeyfile\fR. It is meant for preparing encrypted
partition images without relying on the kernel encryption routines, which
require root privileges to use and may not even be available on the build
system.
'''
.SH OPTIONS
.IP "\fB-d\fR" 4
Decrypt the image instead of encrypting it.
.IP "\fB-s\fR" 4
Single-core processing (default it to use all available CPU cores).
'''
.SH SEE ALSO
\fBdektool\fR(8)
