.TH dektool 1
'''
.SH NAME
\fBdektool\fR \- disk encryption keys manipulation tool
'''
.SH SYNOPSIS
.IP "\fBdektool\fR \fB-c\fR \fIkeyfile\fR [\fIn\fR]" 4
Create \fIkeyfile\fR with \fIn\fR keys.
.IP "\fBdektool\fR \fB-a\fR \fIkeyfile\fR [\fIn\fR]" 4
Add \fIn\fR keys.
.IP "\fBdektool\fR \fB-t\fR \fIkeyfile\fR" 4
Test passphrase.
.IP "\fBdektool\fR \fB-p\fR \fIkeyfile\fR" 4
Change passphrase.
'''
.SH DESCRIPTION
The tool works with NIST-wrapped keyfiles containing one or more keys
indended for disk encryption. The key material in the file is encrypted
with a passphrase-derived key. To apply any changes, the existing data in
the file must be decrypted first, and then the updated data must be encrypted
again. The tool never leaves the file unencrypted.
.P
The keys themselves are just 16-byte chunks of data from /dev/urandom.
There should be one key for each partition being encrypted.
'''
.SH SEE ALSO
\fBdmcrypt\fR(8)
