.TH dektool 8
'''
.SH NAME
\fBdektool\fR \- disk encryption keys manipulation tool
'''
.SH SYNOPSIS
.IP "\fBdektool create\fR \fIkeyfile\fR [\fIn\fR]" 4
Create \fIkeyfile\fR with \fIn\fR keys.
.IP "\fBdektool crover\fR \fIkeyfile\fR [\fIn\fR]" 4
Same, overwriting \fIkeyfile\fR if necessary.
.IP "\fBdektool add\fR \fIkeyfile\fR [\fIn\fR]" 4
Add \fIn\fR keys to \fIkeyfile\fR.
.IP "\fBdektool test\fR \fIkeyfile\fR" 4
Try unwrapping \fIkeyfile\fR to test passphrase.
.IP "\fBdektool repass\fR \fIkeyfile\fR" 4
Change passphrase.
'''
.SH DESCRIPTION
The tool works with AES-wrapped keyfiles containing one or more keys
indended for disk encryption. The key material in the file is encrypted
with a passphrase-derived key. To apply any changes, the existing data in
the file must be decrypted first, and then the updated data must be encrypted
again. The tool never leaves the file unencrypted.
.P
The keys are 32-byte (256-bit) chunks of random data from /dev/urandom.
There should be one key for each partition being encrypted.
'''
.SH SEE ALSO
\fBdmcrypt\fR(8), NIST AES Key Wrap Specification.
