.TH udevmod 8
'''
.SH NAME
\fBudevmod\fR \- udev event monitor / kernel module auto-loader
'''
.SH DESCRIPTION
Some drivers within the kernel include special MODALIAS entry in their udev
events to let the userspace figure out a suitable driver for un-handled devices
sitting on some enumerable buses. When such events arrive, udevmod spawns
\fBmodprobe\fR to check for modules.
.P
In common PC systems, this service is responsible for loading PCI device
drivers, including DRI modules for video output.
.P
This service also provides some compatibility for userspace applications
written around libudev, namely event re-transmission in libudev format and
input device tagging.
'''
.SH FILES
.IP "/etc/udev/modpipe" 4
This script is spawned during startup, and gets a list of module aliases
to be loaded on stdin. See \fBmodprobe\fR(1) pipe-mode, \fB-p\fR.
.IP "/etc/udev/modprobe" 4
This script is spawned whenever a module needs to be loaded past the startup
stage. It most cases it should invoke \fBmodprobe\fR(1).
'''
.SH SEE ALSO
\fBmodprobe\fR(8)
