.TH waitdev 8
'''
.SH NAME
waitdev \- sleep until specified device appears in /dev
'''
.SH SYNOPSIS
waitdev [\fB+\fItimeout\fR] \fIdevice\fR [\fIdevice\fR ...]
'''
.SH DESCRIPTION
During boot device discovery and device nodes allocation in devtmpfs
may happen concurrently with system init scripts, causing race conditions
for early mounts and other commands that depend on device node availability.
.P
The purpose of \fBwaitdev\fR is to stall the script until the nodes become
available. It uses \fBnetlink\fR(7) interface to listen for udev events,
exiting immediately once all listed devices appear.
.P
The tool waits at most 5 seconds (or \fItimeout\fR) for the devices to appear.
.P
Device names must be specified the same way they appear in udev, that is as
"sdb", "sdc" and such, without the /dev prefix.
'''
.SH NOTES
Timeouts are reported with non-zero exit status, but generally should be
ignored. Subsequent commands that actually need the device nodes in question
will likely provide descriptive error messages anyway.
.P
The tool is only meant to be used with non-removable core devices which
get predictable kernel names and do not require additional efforts to identify.
'''
.SH SEE ALSO
\fBudev\fR(7), \fBnetlink\fR(7)
