.TH find 1
'''
.SH NAME
find \- locate files by name
'''
.SH SYNOPSIS
find [\fB-i\fR \fIdir\fR] \fIpattern\fR ...
'''
.SH USAGE
\fBfind\fR scans current directory (or \fIdir\fR if given) and prints
all files whose names start with \fIpattern\fR.
.P
Patterns starting with a dot match at the end of the file name.
Searching for \fB.c\fR will yield the list of all C source files
in current directory and its subdirectories.
'''
.SH SEE ALSO
\fBlist\fR(1)
