.TH head 1
'''
.SH NAME
\fBhead\fR \- output initial lines of a file
'''
.SH SYNOPSIS
\fBhead\fR [\fB-\fIN\fR] [\fIfile\fR]
'''
.SH NOTES
The default value for \fIN\fR is 10.
.P
This particular implementation may output less than \fBN\fR lines
if the lines in the file are very long.
'''
.SH SEE ALSO
\fBtail\fR(1)
