bin = basename chvt dirname echo false head kill mkdir pwd rm rmdir \
      sleep tee touch true uname uptime wc xargs yes

man1 = echo.1 kill.1 mkdir.1 pwd.1 rm.1 rmdir.1 sleep.1 tee.1 \
       touch.1 uname.1 wc.1 xargs.1 yes.1

include ../rules.mk
