.TH sync 1
'''
.SH NAME
sync \- synchronize cached writes to persistent storage
'''
.SH SYNOPSIS
sync [\fB-fd\fR] [\fIfile\fR ...]
'''
.SH DESCRIPTION
sync requests writes to be performed, and waits until the kernel
reports completion. If one or more \fIfile\fR name is given,
the request is only made for those files.
'''
.SH OPTIONS
.IP "\fB-d\fR" 4
Sync file data only, do not request metadata (mtime, atime) write.
.IP "\fB-f\fR" 4
Sync all writes for the filesystem containing \fIfile\fR.
'''
.SH SEE ALSO
\fBsync\fR(2), \fBfsync\fR(2), \fBsyncfs\fR(2), \fBfdatasync\fR(2).
