.TH insmod 8
'''
.SH NAME
insmod \- insert (load) kernel module
'''
.SH SYNOPSIS
insmod \fImodule.ko\fR [\fIparameters\fR]
'''
.SH DESCRIPTION
insmod attempts to load a single module into the kernel.
The \fImodule\fR argument must be a file name, not a module name
as used by \fBrmmod\fR and listed by \fBlsmod\fR.
.P
Optional \fIparameters\fR argument is passed directly to the module.
'''
.SH SEE ALSO
\fBinit_module\fR(2)
