.TH rmmod 8
'''
.SH NAME
rmmod \- remove (unload) kernel module
'''
.SH SYNOPSIS
rmmod [\fB-fw\fR] \fImodule\fR ...
'''
.SH DESCRIPTION
rmmod requests module removal from the kernel.
Modules are only removed if not in use, otherwise the request fails.
.P
\fB-f\fR forces removal even if the module is in use. DANGEROUS.
.P
\fB-w\fR make the request block until the module is removed.
.P
Internal kernel module name as reported by \fBlsmod\fR(1) must be used
for \fImodule\fR argument. Typically, but not necessary, it is the basename
of the module file with .ko extension removed.
'''
.SH SEE ALSO
\fBdelete_module\fR(2)
