.TH write 1
'''
.SH NAME
write \- write strings to file
'''
.SH SYNOPSIS
write [\fB-caxtlym\fR] \fIfile\fR \fItext\fR \fItext\fR ...
.br
write \fB-m\fR[\fBcaxtly\fR] \fImode\fR \fIfile\fR \fItext\fR \fItext\fR ...
'''
.SH DESCRIPTION
Arguments \fItext\fR \fItext\fR ... get written to \fIfile\fR, the same
way \fBecho\fR \fItext\fR \fItext\fR ... > \fIfile\fR would but without
the need to rely on shell redirects.
'''
.SH OPTIONS
The options define how \fBopen\fR(2) will be called on \fIfile\fR.
.IP "\fB-c\fR" 4
Create \fIfile\fR if it does not exist (O_CREAT).
.IP "\fB-a\fR" 4
Append to \fIfile\fR (O_APPEND).
.IP "\fB-x\fR" 4
Create file exclusively, fail if the file already exists (O_EXCL).
.IP "\fB-t\fR" 4
Do not update file access time (O_NOATIME).
.IP "\fB-y\fR" 4
Make writes synchronous (O_SYNC).
.IP "\fB-m\fR" 4
Specify file creation mode. Only makes sense with \fB-c\fR or \fB-x\fR.
'''
.SH SEE ALSO
\fBecho\fR(1), \fBopen\fR(2), \fBwrite\fR(2).
