#include <bits/errno.h>
#include <fail.h>
#include <null.h>

/* Default tag & error list for those utils that do not need
   a custom one. This should include common error for common
   syscalls. */

#define weak __attribute__((weak))

ERRTAG weak = "";

ERRLIST weak = {
	REPORT(EPERM), REPORT(ENOENT), REPORT(EINTR), REPORT(EIO),
	REPORT(EBADF), REPORT(EAGAIN), REPORT(ENOMEM), REPORT(EACCES),
	REPORT(EFAULT), REPORT(EBUSY), REPORT(EEXIST), REPORT(ENOTDIR),
	REPORT(EISDIR), REPORT(EINVAL), REPORT(ENFILE), REPORT(EMFILE),
	REPORT(ENOTTY), REPORT(ENOSPC), REPORT(EROFS), REPORT(EMLINK),
	REPORT(ENAMETOOLONG), REPORT(ENOSYS), REPORT(ELOOP),
	REPORT(EBADMSG), REPORT(EOPNOTSUPP), REPORT(EADDRINUSE),
	REPORT(ENOBUFS), REPORT(ETIMEDOUT), REPORT(EALREADY),
	RESTASNUMBERS
};
