.TH inputs 1
'''
.SH NAME
\fBinputs\fR \- list input devices
'''
.SH SYNOPSIS
.IP "\fBinputs\fR [\fB-a\fR]" 4
List all input devices [and their capabilities].
.IP "\fBinputs\fR \fIeventN\fR \fIeventN\fR ..." 4
List event capabilities for given devices.
.IP "\fBinputs\fR \fB-r\fR \fIeventN\fR" 4
Read and dump events from a given device.
'''
.SH DESCRIPTION
This tool lists input event devices along with their human-readable names
and the events each device can generate. Its purpose is figuring out how
physical devices map onto Linux device nodes and which event codes get
generated in response to certain actions.
'''
.SH FILES
.IP "/dev/input/event*" 4
Input devices.
'''
.SH NOTES
Reading raw input devices (\fBinputs -r\fR) usually requires root privileges.
'''
.SH SEE ALSO
\fBkeymon\fR(8), linux/include/uapi/input-event-codes.h
