.TH acpid 8
'''
.SH NAME
\fBacpid\fR \- ACPI event daemon
'''
.SH DESCRIPTION
\fBacpid\fR listens for ACPI events over netlink interface, filters those
few that may require handling, and spawns handler scripts:
'''
.IP "/etc/acpi/acpower" 4
AC power adapter has been connected.
.IP "/etc/acpi/battery" 4
AC adapter has been disconnected, the device is on battery power.
.IP "/etc/acpi/sleep" 4
Sleep button pressed.
.IP "/etc/acpi/power" 4
Power button pressed.
'''
.SH NOTES
There are apparently no ACPI events for low battery levels.
.P
Power and Sleep button events may also be available via the input
subsystem; see \fBinputs\fR(1) and \fBkeymon\fR(8).
