.TH lindevd 8
'''
.SH NAME
\fBlindevd\fR \- libinput device tagger daemon
'''
.SH DESCRIPTION
Libinput and applications based on libinput need certain device identification
data in /run/udev/data to work properly. In conventional systems that data is
provided (written) by udevd with a bunch of rule files. This daemon emlulates
relevant functionality, allowing libudev applications to run on otherwise
udev-free systems.
.P
Note this daemon is an ugly hack that should not exist in a properly written
system. There is no reason for libinput to rely on 3rd-party files to get the
data it could just as well query itself. Current implementation does only the
absolute minimum necessary to run unpatched weston with unpatched libinput;
once the problem is fixed where it should be fixed, there will be no reason
to run this daemon at all.
'''
.SH FILES
.IP "/dev/input/" 4
Input devices.
.IP "/run/udev/data/" 4
Stored device identification data.
