.TH modprobe 8
'''
.SH NAME
\fBmodprobe\fR \- load or unload kernel modules
'''
.SH SYNOPSIS
.IP "\fBmodprobe\fR \fImodule\fR [\fIoptions\fR]" 4
Load single module, optionally overriding its configured options.
.IP "\fBmodprobe\fR \fB-a\fR \fImodule\fR \fImodule\fR ..." 4
Load specified modules with default options.
.IP "\fBmodprobe\fR \fB-r\fR \fImodule\fR \fImodule\fR ..." 4
Unload specified modules and if possible their dependencies.
'''
.SH FILES
.IP "/lib/modules/$RELEASE" 4
Base directory to look for modules.
.IP "/lib/modules/$RELEASE/modules.dep" 4
List of module paths and dependencies. 
.IP "/etc/modopts" 4
Pre-configured module options.
.P
$RELEASE is the running kernel release as returned by \fBuname\fR(2).
'''
.SH SEE ALSO
\fBinit_module\fR(2), \fBdelete_module\fR(2), \fBdepmod\fR(1).
