.TH modprobe 1
'''
.SH NAME
\fBmodprobe\fR \- load or unload kernel modules
'''
.SH SYNOPSIS
.IP "\fBmodprobe\fR \fImodule\fR [\fIoptions\fR]" 4
Load single module, optionally overriding its configured options.
.IP "\fBmodprobe\fR \fB-a\fR \fImodule\fR \fImodule\fR ..." 4
Load specified modules with default options.
.IP "\fBmodprobe\fR \fB-r\fR \fImodule\fR \fImodule\fR ..." 4
Unload specified modules and if possible their dependencies.
.IP "\fBmodprobe\fR \fB-b\fR \fIbasedir\fR ..." 4
Use specified base directory instead of /lib/modules/$RELEASE.
'''
.SH OPTIONS
.IP "\fB-a\fR" 4
Treat all arguments as module names.
.IP "\fB-b\fR" 4
Use specified base directory.
.IP "\fB-n\fR" 4
Dry run. Show actions to be performed, but do not perform them.
.IP "\fB-r\fR" 4
Remove specified modules and their dependencies from the kernel.
.IP "\fB-q\fR" 4
Suppress some error messages and skip blacklisted modules.
.IP "\fB-p\fR" 4
Pipe mode; read module names from stdin.
.IP "\fB-v\fR" 4
Show actions being performed and also perform them.
'''
.SH NOTES
This version of \fBmodprobe\fR natively supports lzip-compressed modules
(.ko.lz) and can handle gzip or xz compresses modules (.ko.gz, .ko.xz)
if \fBzcat\fR or \fBxzcat\fR respectively are present in PATH. For this
to work, modules.dep must list compressed file names.
'''
.SH FILES
.IP "/lib/modules/$RELEASE" 4
Base directory to look for modules.
.IP "/lib/modules/$RELEASE/modules.dep" 4
List of module paths and dependencies. 
.IP "/etc/modules" 4
Configuration file.
.P
$RELEASE is the running kernel release as returned by \fBuname\fR(2).
'''
.SH SEE ALSO
\fBinit_module\fR(2), \fBdelete_module\fR(2), \fBdepmod\fR(1).
