.TH ifctl 1
'''
.SH NAME
\fBifctl\fR \- control tool for \fBifmon\fR(8)
'''
.SH SYNOPSIS
Set persistent configuration for the interface:
.IP "\fBifctl\fR \fB-x\fR \fIiface\fR" 4
Skip mode, \fBifmon\fR will not touch this interface.
.IP "\fBifctl\fR \fB-d\fR \fIiface\fR" 4
Down mode, \fBifmon\fR will bring this interface down.
.IP "\fBifctl\fR \fB-a\fR \fIiface\fR" 4
Auto mode, \fBifmon\fR will try to run \fBdhcp\fR(1) on this interface.
.IP "\fBifctl\fR \fB-w\fR \fIiface\fR" 4
Wi-Fi client mode, \fBwsupp\fR(8) will be started on this interface.
.P
Change interface state temporarily:
.IP "\fBifctl\fR \fB-r\fR \fIiface\fR" 4
Re-active the interface and re-start any associated processes.
.IP "\fBifctl\fR \fB-n\fR \fIiface\fR" 4
Deactivate interface, stop any associated processes.
'''
.SH SEE ALSO
\fBifmod\fR(8), \fBwifi\fR(1), \fBwsupp\fR(8).
