include ../config.mk

sbin = mount mountvfs umount insmod rmmod mknod switchroot fstrim \
	systime chvt dmesg uptime

man8 = insmod.8 mount.8 mountvfs.8 rmmod.8 systime.8 umount.8 fstrim.8 \
	dmesg.8 uptime.8

include ../common.mk
