.TH sysinfo 8
'''
.SH NAME
sysinfo \- print system stats
'''
.SH SYNOPSIS
sysinfo
'''
.SH DESCRIPTION
This tool calls \fBsysinfo\fR(2) and outputs the data in a human-readable
format. The output includes uptime, number of processes running, load
averages and memory sizes.
'''
.SH SEE ALSO
\fBsysinfo\fR(2), \fBuptime\fR(8)
