.TH date 1
'''
.SH NAME
date \- show local time and convert time between time zones
'''
.SH SYNOPSIS
.IP "\fBdate\fR [\fItimezone\fR]" 4
Show current local time, or current time in \fItimezone\fR.
.IP "\fBdate\fR [\fItimezone\fR] \fItimestamp\fR" 4
Show \fItimestamp\fR in local or specified \fItimezone\fR.
.IP "\fBdate\fR [\fItimezone\fR] [\fIY\fB-\fIM\fB-\fID\fR] \fIhh\fB:\fImm\fR[:\fIss\fR] [\fItz\fR]" 4
Convert specified time to \fItimezone\fR.
'''
.SH NOTES
Timezones may be given as abbreviations (PDT, EEST, UTC-5) or as
\fBtzdata\fR zone names (US/Pacific).
'''
.SH FILES
Zone definitions are usually provided by \fBtzdata\fR package.
.IP "/etc/localtime" 4
Local time zone definition.
.IP "/usr/share/zoneinfo" 4
Locations to look for named zones.
'''
.SH ENVIRONMENT
.IP "TZ" 4
Local time zone name. If defined, overrides /etc/localtime.
.br
Any name valid for \fItimezone\fR argument is valid in \fB$TZ\fR
as well.
'''
.SH SEE ALSO
\fBsystime\fR(8), \fBtzfile\fR(5)
