.TH delete 1
'''
.SH NAME
\fBdelete\fR \- delete files and directories
'''
.SH SYNOPSIS
\fBdelete\fR [\fB-fndxZ\fR] \fIfile\fR \fIfile\fR ...
'''
.SH OPTIONS
.IP "\fB-n\fR" 4
Remove named files only / do not enter directories.
.IP "\fB-f\fR" 4
Continue as far as possible regardless of errors.
.IP "\fB-d\fR" 4
Call \fBrmdir\fR(2) for each specified \fIfile\fR.
.IP "\fB-x\fR" 4
Do cross filesystem boundaries.
.IP "\fB-Z\fR" 4
Do remove / (the root node) if asked to.
'''
.SH NOTES
Unless \fB-x\fR is given, \fBdelete\fR does not cross filesystem boundaries.
'''
.SH SEE ALSO
\fBunlinkat\fR(2)
