all = bincopy calendar copy date delete find list locfg
all += pskill pslist pstree sync mntstat sysinfo systime

include ../rules.mk

date: date.o date_find.o date_time.o

copy: copy.o copy_tree.o copy_file.o
