/=../
include ../config.mk
include ../common.mk

all = mount mountvfs umount insmod rmmod mknod

all: $(all)

mount: mount.o

mountvfs: mountvfs.o

umount: umount.o

insmod: insmod.o

rmmod: rmmod.o

mknod: mknod.o
