.TH rm 8
'''
.SH NAME
rm \- remove files or directories
'''
.SH SYNOPSIS
rm [\fB-frdx\fR] \fIfile\fR \fIfile\fR ...
'''
.SH DESCRIPTION
rm removes (deletes) specified files.
With \fB-r\fR, it removes the directories and their contents recursively.
.P
Without \fB-f\fR, rm stops at the first error. rm never follows symlinks.
rm refuses to delete / unless \fB-R\fR is given.
.P
Unless \fB-x\fR is given, rm does not cross filesystem boundaries. Any entries
removed recursively under each of the \fIfile\fR argument must have the same
st_dev per \fBstat\fr(2) as the \fIfile\fR argument itself.
'''
.SH OPTIONS
.IP "\fB-r\fR" 4
Remove directories recursively.
.IP "\fB-f\fR" 4
Continue as far as possible regardless of errors.
.IP "\fB-d\fR" 4
Assume \fIfile\fRs are in fact directories, and call \fBrmdir\fR(2).
.IP "\fB-x\fR" 4
Do cross filesystem boundaries.
.IP "\fB-R\fR" 4
Do remove / (the root node) if asked to.
'''
.SH SEE ALSO
\fBunlink\fR(2), \fBrmdir\fR(2), \fBstat\fR(2).
