.TH cat 1
'''
.SH NAME
\fBcat\fR \- concatenate files
'''
.SH SYNOPSIS
.IP "\fBcat\fR \fIfile\fR \fIfile\fR ..." 4
Dump contents of \fIfile\fR(s) to stdout.
.IP "\fBcat -e\fR \fIfile\fR \fIfile\fR ..." 4
Dump contents of \fIfile\fR(s) to stderr.
.IP "\fBcat -o\fR \fIoutput\fR \fIfile\fR \fIfile\fR ..." 4
Dump contents of \fIfile\fR(s) into \fIoutput\fR.
.IP "\fBcat -a\fR \fIoutput\fR \fIfile\fR \fIfile\fR ..." 4
Append contents of \fIfile\fR(s) to \fIoutput\fR.
'''
.SH SEE ALSO
\fBtee\fR(1)
