.TH cat 1
'''
.SH NAME
\fBcat\fR \- concatenate files
'''
.SH SYNOPSIS
.IP "\fBcat\fR \fIfile\fR \fIfile\fR ..." 4
Dump contents of \fIfile\fR(s) onto the standard output.
.IP "\fBcat\fR \fB-o\fR \fIoutput\fR \fIfile\fR \fIfile\fR ..." 4
Dump contents of \fIfile\fR(s) into \fIoutput\fR.
.IP "\fBcat\fR \fB-a\fR \fIoutput\fR \fIfile\fR \fIfile\fR ..." 4
Append contents of \fIfile\fR(s) to \fIoutput\fR.
'''
.SH SEE ALSO
\fBtee\fR(1)
