.TH cpy 1
'''
.SH NAME
\fBcpy\fR \- copy files and directories
'''
.SH SYNOPSIS
.IP "\fBcpy\fR \fB-h\fR \fIpath\fR \fIpath\fR ..." 4
Copy the last component of each \fIpath\fR into current directory.
.IP "\fBcpy\fR \fB-t\fR \fIdir\fR \fIpath\fR \fIpath\fR ..." 4
Copy the last component of each \fIpath\fR into \fIdir\fR.
.IP "\fBcpy\fR \fB-n\fR \fIdst\fR \fIsrc\fR" 4
Make a copy of \fIsrc\fR named \fIdst\fR.
.IP "\fBcpy\fR \fB-o\fR \fIdst\fR \fIsrc\fR" 4
Copy \fIsrc\fR over \fIdst\fR.
'''
.SH OPTIONS
.IP "\fB-h\fR" 4
Copy here; destination is the current directory.
.IP "\fB-m\fR" 4
Move files instead of copying them.
.IP "\fB-n\fR" 4
Do not overwrite anything.
.IP "\fB-o\fR" 4
Copy over, silently overwriting existing files.
.IP "\fB-t\fR" 4
Copy to; destination directory is the first argument.
.IP "\fB-u\fR" 4
Transfer file ownership (uid/gid) to the copies.
'''
.SH NOTES
\fBcpy\fR never follows symlinks, and copies them as if they were plain text
files. Other special files are silently ignored.
