.TH ls 1
'''
.SH NAME
\fBls\fR \- list current directory
'''
.SH SYNOPSIS
\fBls\fR [\fB-auy\fR] \fIpattern\fR \fIpattern\fR ...
'''
.SH OPTIONS
.IP "\fB-a\fR" 4
Include hidden files in the list.
.IP "\fB-u\fR" 4
Produce uniform list, do not sort directories before files.
.IP "\fB-y\fR" 4
List symlinks as files regardless of their targets.
'''
.SH NOTES
ls sorts its output by raw byte values. This is done only to ensure stable
output not dependent on irrelevant filesystem information. Locale settings
do not affect the ordering.
.P
ls never lists . and .. special entries.
Those are assumed to be present in any directory.
.P
This version of ls does not support \fB-l\fR listing format.
'''
.SH SEE ALSO
\fBstat\fR(1), \fBlr\fR(1), \fBgetdents\fR(2)
