.TH ps 1
'''
.SH NAME
\fBps\fR \- process list
'''
.SH SYNOPSIS
.IP "\fBps\fR" 4
List all userspace processes.
.IP "\fBps\fR \fIprefix\fR" 4
List userspace processes starting with \fIprefix\fR and their ancestors.
.IP "\fBps -k\fR" 4
List in-kernel processes.
'''
.SH NOTES
All proper userspace processes are descendants of pid 1 (init).
In-kernel processes have their own hierarchy, typically rooted
at pid 2 (kthreadd).
