/ = ../../

all = \
      basename \
      cat \
      chmod \
      chown \
      chvt \
      clear \
      dirname \
      du \
      echo \
      false \
      fn \
      head \
      lr \
      mkdir \
      mknod \
      pwd \
      ren \
      rm \
      rmdir \
      sleep \
      stat \
      symlink \
      tee \
      time \
      touch \
      true \
      uname \
      uptime \
      wc \
      which \
      xargs \
      yes

include ../rules.mk
include $/config.mk

-include *.d
