.TH yes 1
'''
.SH NAME
yes \- output a string repeatedly until killed
'''
.SH SYNOPSIS
yes
.br
yes \fIstring\fR ...
'''
.SH DESCRIPTION
yes prints "y" or \fIstring\fR in an endless loop.
.P
The output of this tool should be piped to something that expects
interacitve user confirmation, as in "proceed? [Y/n]" and similar.
'''
.SH SEE ALSO
\fBecho\fR(1)
