/=../
include ../config.mk
include ../common.mk

all = strerror mkdir cat clear write rmdir

all: $(all)

strerror: strerror.o

mkdir: mkdir.o

cat: cat.o

clear: clear.o

write: write.o

rmdir: rmdir.o
