#define CMD_RESET      0
#define CMD_LIST       1
#define CMD_STATUS     2
#define CMD_GETPID     3
#define CMD_FLUSH      4
#define CMD_QUERY      5
#define CMD_START      6
#define CMD_RESTART    7
#define CMD_STOP       8
#define CMD_PAUSE      9
#define CMD_RESUME    10
#define CMD_HUP       11
#define CMD_RELOAD    12
#define CMD_REBOOT    13
#define CMD_SHUTDOWN  14
#define CMD_POWEROFF  15

#define ATTR_PROC     1
#define ATTR_NAME     2
#define ATTR_CODE     3
#define ATTR_PID      4
#define ATTR_RING     5
