.TH svcctl 1
'''
.SH NAME
\fBsvcctl\fR \- system service control tool.
'''
.SH DESCRIPTION
This tool sends commands to \fBsvchub\fR(8) and pretty-prints the responses.
'''
.SH USAGE
.IP "\fBsvcctl\fR" 4
List system services.
.IP "\fBsvcctl show \fIname\fR" 4
Show status of a given service.
.IP "\fBsvcctl flush \fIname\fR" 4
Empty the ring buffer of a named service.
.IP "\fBsvcctl\fR {\fBstart\fR|\fBstop\fR|\fBrestart\fR} \fIname\fR" 4
Spawn of kill named service.
.IP "\fBsvcctl\fR \fBhup\fR \fIname\fR" 4
Send SIGHUP to the service.
.IP "\fBsvcctl\fR \fBreload\fR" 4
Re-scan config directory and update the list of services.
.IP "\fBsvcctl\fR {\fBreboot\fR|\fBhalt\fR|\fBpoweroff\fR}" 4
Stop all services and then the system itself.
'''
.SH FILES
.IP "/run/ctrl/svhub" 4
Control socket.
'''
.SH SEE ALSO
\fBsvchub\fR(8)
