.TH svctl 8
'''
.SH NAME
\fBsvctl\fR \- supervisor control tool.
'''
.SH DESCRIPTION
This tool sends commands to \fBsuper\fR(8) and pretty-prints the responses.
'''
.SH USAGE
.IP "\fBsvctl\fR\ " 4
List supervised processes.
.IP "\fBsvctl \fIname\fR" 4
Show status of a given service.
.IP "\fBsvctl \fB-\fR[\fBstr\fR] \fIname\fR \fIname\fR ..." 4
\fBS\fRtart, s\fBt\fRop or \fBr\fRestart given services.
.IP "\fBsvctl \fB-\fR[\fBuw\fR] \fIname\fR \fIname\fR ..." 4
S\fBu\fRspend or resume (\fBw\fRake up) given services.
.IP "\fBsvctl \fB-\fR\fBh\fR \fIname\fR \fIname\fR ..." 4
Send SIGHUP to given services.
.IP "\fBsvctl \fB-q\fR" 4
Re-scan directory / reload services list.
.IP "\fBsvctl \fB-\fR[\fBRHP\fR]" 4
Stop all services and proceed to \fBr\fReboot/\fBh\fRalt\fR/\fBp\fRoweroff.
'''
.SH FILES
.IP "/run/super" 4
Control socket.
'''
.SH SEE ALSO
\fBsuper\fR(8)
