.TH svctl 1
'''
.SH NAME
\fBsvctl\fR \- supervisor control tool.
'''
.SH DESCRIPTION
This tool sends commands to \fBsuper\fR(8) and pretty-prints the responses.
'''
.SH USAGE
.IP "\fBsvctl\fR" 4
List supervised processes.
.IP "\fBsvctl show \fIname\fR" 4
Show status of a given service.
.IP "\fBsvctl flush \fIname\fR" 4
Empty the ring buffer of a named process.
.IP "\fBsvctl\fR {\fBstart\fR|\fBstop\fR|\fBrestart\fR} \fIname\fR \fIname\fR ..." 4
Spawn of kill named processes.
.IP "\fBsvctl\fR {\fBsuspend\fR|\fBresume\fR|\fBhup\fR} \fIname\fR \fIname\fR ..." 4
Send SIGSTOP/SIGCONT/SIGHUP repectively.
.IP "\fBsvctl\fR \fBreload\fR" 4
Re-scan config directory and update the list of services.
.IP "\fBsvctl\fR {\fBreboot\fR|\fBhalt\fR|\fBpoweroff\fR}" 4
Stop all services and then the system itself.
'''
.SH FILES
.IP "/run/ctrl/super" 4
Control socket.
'''
.SH SEE ALSO
\fBsuper\fR(8)
