include ../../config.mk

bin = uname

sbin = mount mountvfs umount insmod rmmod switchroot fstrim \
	systime dmesg uptime sysinfo

man8 = insmod.8 mount.8 mountvfs.8 rmmod.8 systime.8 umount.8 fstrim.8 \
	dmesg.8 uptime.8 sysinfo.8 uname.1

include ../../common.mk
