.TH umount 8
'''
.SH NAME
umount \- detach mounted filesystem trees
'''
.SH SYNOPSIS
umount [\fB-fdxn\fR] \fIdir\fR \fIdir\fR \fIdir\fR ...
'''
.SH DESCRIPTION
umount detaches mounted filesystems from file system hierarchy.
'''
.SH OPTIONS
Any combination of the options below must be squashed into a single argument:
\fB-nx\fR is accepted but \fB-n -x\fR is not.
.P
The options are bits in \fBflags\fR argument for \fBumount\fR(2) system call.
Refer to that page for more info.
.IP "\fB-f\fR" 4
Force unmounting (MNT_FORCE).
.IP "\fB-d\fR" 4
Perform a lazy unmount (MNT_DETACH).
.IP "\fB-x\fR" 4
Make mount point as expired (MNT_EXPIRE).
.IP "\fB-n\fR" 4
Do not follow symlinks (UMOUNT_NOFOLLOW).
'''
.SH NOTES
This tool does not read /etc/fstab and does not update /etc/mtab.
'''
.SH SEE ALSO
\fBumount\fR(2), \fBmount\fR(8).
