.TH wictl 1
'''
.SH NAME
wictl \- \fBwimon\fR(8) control tool
'''
.SH USAGE
.IP "\fBwictl\fR" 4
Show current configuration.
.IP "\fBwictl\fR \fB-s\fR [\fIdevice\fR]" 4
Scan for available stations.
.IP "\fBwictl\fR [\fB-p\fR] \fIssid\fR" 4
.IP "\fBwictl\fR [\fB-p\fR] \fIbssid\fR" 4
Connect to specified AP, asking for passphrase if \fB-p\fR was specified.
.IP "\fBwictl\fR \fB-w\fR \fIdevice\fR" 4
Connect to any available network in range that \fBwimon\fR(8) has got
a saved PSK for.
.IP "\fBwictl\fR \fB-e\fR [\fIdevice\fR] [\fI0.0.0.0/0\fR] 4
Switch to a wired connection on \fIdevice\fR. Device will be configured
with \fBdhcp\fR(8) if ip address is not specified.
.IP "\fBwictl\fR \fB-d\fR" 4
Disconnect all interfaces.
'''
.SH FILES
.IP "/run/wimon" 4
\fBwimon\fR(8) control socket.
'''
.SH SEE ALSO
\fBwimon\fR(8)
