.TH wimon 8
'''
.SH NAME
wimon \- Wi-Fi and Ethernet networking device monitor
'''
.SH DESCRIPTION
As a device monitor, wimon tracks networking devices present in the system,
their enabled/disabled state, and spawns child processes to apply persistent
configuration.
.P
As a Wi-Fi monitor, it also performs scans to discover available networks
and connects to known networks using saved credentials (PSKs).
'''
.SH USAGE
wimon is a long-running background process that should be started during
system startup. All user interaction with wimon must happen through its
control socket, see \fBwictl\fR(1).
'''
.SH FILES
.IP "/var/wimon.state" 4
Saved device configuration and PSKs for known networks.
.IP "/run/ctrl/wimon" 4
Control socket.
.P
\fBdhcp\fR(8) and \fBwpa\fR(8) commands should be available in $PATH.
'''
.SH SEE ALSO
\fBwictl\fR(1), \fBdhcp\fR(8), \fBwpa\fR(8), \fBnetlink\fR(7).
