.TH wsupp 8
'''
.SH NAME
\fBwsupp\fR \- WPA supplicant (Wi-Fi client software)
'''
.SH SYNOPSIS
\fBwsupp\fR \fIwlan0\fR
'''
.SH DESCRIPTION
A long-running process that implements userspace parts of a Wi-Fi client.
In most cases should only be started under \fBifmon\fR(8) using either
\fBwifi\fR(1) or \fBifctl\fR(1). See \fBwifi\fR(1) for available user commands.
'''
.SH FILES
.IP "/run/ctrl/wsupp" 4
Control socket.
.IP "/var/wipsk" 4
Pre-shared keys for known access points.
'''
.SH SEE ALSO
\fBwifi\fR(1), \fBifctl\fR(1), \fBifmon\fR(8).
