.TH hexdump 1
'''
.SH NAME
hexdump \- display file contents in hexadecimal notation
'''
.SH SYNOPSIS
hexdump [\fIfile\fR]
'''
.SH DESCRIPTION
For each of 16 byte blocks in \fIfile\fR hexdump shows its offset
within the file, byte values, and printable characters.
.P
In case no \fIfile\fR is given, hexdump reads standard input.
