.TH del 8
'''
.SH NAME
del \- delete files or directories
'''
.SH SYNOPSIS
del [\fB-frdxZ\fR] \fIfile\fR \fIfile\fR ...
'''
.SH DESCRIPTION
del deletes specified files.
.P
Unless \fB-x\fR is given, del does not cross filesystem boundaries.
Any entries removed recursively under each of the \fIfile\fR argument
must have the same st_dev per \fBstat\fr(2) as the \fIfile\fR argument
itself.
'''
.SH OPTIONS
.IP "\fB-r\fR" 4
Remove directories recursively.
.IP "\fB-f\fR" 4
Continue as far as possible regardless of errors.
.IP "\fB-d\fR" 4
Assume \fIfile\fRs are in fact directories, and call \fBrmdir\fR(2).
.IP "\fB-x\fR" 4
Do cross filesystem boundaries.
.IP "\fB-Z\fR" 4
Do remove / (the root node) if asked to.
'''
.SH SEE ALSO
\fBunlink\fR(2), \fBrmdir\fR(2), \fBstat\fR(2).
