.TH tee 1
'''
.SH NAME
tee \- copy stream to a file
'''
.SH SYNOPSIS
tee [\fB-a\fR] \fIfile\fR
'''
.SH DESCRIPTION
tee passes data from stdin to stdout without changing it,
and also writes the same data to \fIfile\fR.
'''
.SH OPTIONS
.IP "\fB-a\fR" 4
append to \fIfile\fR instead of overwriting it.
'''
.SH SEE ALSO
\fBcat\fR(1), \fBecho\fR(1).
