.TH kill 1
'''
.SH NAME
kill \- terminate a process
'''
.SH SYNOPSIS
kill [\fB-\fIsignal\fR] \fIpid\fR ...
'''
.SH DESCRIPTION
kill sends SIGTERM (or \fIsignal\fR) to specified processes.
.P
Signal can be either a raw number, or a constant like TERM, KILL and so on.
See \fBsignal\fR(7) for a full list of possible signals and their descriptions.
.P
Killing a negative \fIpid\fR sends the signal to the whole process group.
Pids 0 and -1 have special meaning. See \fBkill\fR(2) on this.
'''
.SH SEE ALSO
\fBkill\fR(2), \fBsignal\fR(7)
