.TH sockmod 8
'''
.SH NAME
\fBsockmod\fR \- service control sockets access mode daemon
'''
.SH DESCRIPTION
Default permissions for control sockets created by various services
generally prevent non-privileged users from connecting to them.
\fBsockmod\fR allows modifying socket permissions without affecting
the services themselves, making them connectable for a given group
or for all users of the system.
'''
\fBsockmod\fR does that by monitoring the directory where the sockets
are supposed to be with \fBinotify\fR(2) and doing \fBchmod\fR(2) or
\fBchown\fR(2) on newly-created files if necessary.
'''
.SH CONFIGURATION
The only configuration file is /etc/sockmod, a plain text file in the
following format:
.P
.nf
    \fIname\fB:\fR \fIgroup\fR
.fi
.P
This line instructs \fBsockmod\fR to make /run/ctrl/\fIname\fR
connectable (writable) for \fIgroup\fR.
A special group name \fB*\fR (asterisk) can be used to make the socket
connectable for all users.
.P
Lines starting with \fB#\fR and empty lines are ignored.
'''
.SH FILES
.IP "/etc/sockmod" 4
Configuration file.
.IP "/run/ctrl/" 4
Directory containing control sockets.
.IP "/etc/group" 4
Name to id mapping for groups.
'''
.SH SEE ALSO
\fBinotify\fR(7), \fBchown\fR(1), \fBchmod\fR(1)
