.TH xorgvt 8
'''
.SH NAME
\fBxorgvt\fR \- start Xorg server with a client on a VT
'''
.SH SYNOPSIS
\fBxorgvt\fR [\fB+\fIversion\fR] [\fB:\fIN\fR] [\fIclient\fR]
'''
.SH DESCRIPTION
This tool is a special version of \fBxinit\fR(1) inteded for running Xorg
server on a VT controlled by \fBvtmux\fR(8). Running Xorg under \fBvtmux\fR
implies particular system setup and requires special treatment for the
control channel (file descriptor 3).
.P
X servers do not spawn their clients. Instead, a dedicated tool (\fBxinit\fR
or in this case \fBxorgvt\fR) is used to spawn the server and the top client
as sibling processes and monitor them until either exits.
'''
.SH FILES
.IP "\fB/etc/X11/server" 4
Default server startup script.
.IP "\fB/etc/X11/server-\fIversion\fR" 4
Custom server startup script.
.IP "\fB/etc/X11/client" 4
Default client startup script.
.IP "\fB/etc/X11/start-\fIclient\fR" 4
Custom client startup script.
'''
.SH ENVIRONMENT
.IP "\fBPATH\fR" 4
Used to locate \fIclient\fR and \fBXorg\fR.
.IP "\fBWESTON_LAUNCHER_SOCK" 4
Must be set to "3".
.IP "\fBWESTON_\fR*" 4
Any variable such will be removed from \fIclient\fR's environment.
.IP "\fBDISPLAY\fR" 4
X display number. Will be set to "\fB:\fIN\fR" for both \fIclient\fR
and \fIserver\fR.
'''
.SH SEE ALSO
\fBxinit\fR(1)
