.TH xorgvt 8
'''
.SH NAME
\fBxorgvt\fR \- start Xorg server with a client on a VT
'''
.SH SYNOPSIS
.IP "\fBxorgvt\fR [\fB-v\fR] \fB:\fIN\fR \fIclient\fR [\fIargs\fR] \
[\fB--\fR \fIserver-args\fR]" 4
Run \fBXorg\fR with \fIclient\fR.
.IP "\fBxorgvt\fR \fB-s\fR \fIserver\fR \fB:\fIN\fR \fIclient\fR \
[\fIargs\fR] [\fB--\fR \fIserver-args\fR]" 4
Run specified server instead of \fBXorg\fR.
.IP "\fBxorgvt\fR \fB-a\fR \fIserver\fR \fB:\fIN\fR [\fIargs\fR] \
\fB--\fR \fIclient\fR [\fIargs\fR]" 4
Same, with complete command specification for both client and server.
.P
\fIclient\fR should be a window manager or a desktop environment startup
executable. \fIN\fR is display number.
'''
.SH DESCRIPTION
This tool is a special version of \fBxinit\fR(1) inteded for running Xorg
server on a VT controlled by \fBvtmux\fR(8). Running Xorg under \fBvtmux\fR
implies particular system setup and requires special treatment for the
control channel (file descriptor 3).
.P
X servers do not spawn their clients. Instead, a dedicated tool (\fBxinit\fR
or in this case \fBxorgvt\fR) is used to spawn the server and the top client
as sibling processes and monitor them until either exits.
'''
.SH OPTIONS
.IP "\fB-a\fR" 4
Alternative command specification, see above.
.IP "\fB-s\fR" 4
Explicit X server specification, see above.
.IP "\fB-v\fR" 4
Verbose mode; pass \fB-verbose 4\fR to \fIserver\fR.
'''
.SH ENVIRONMENT
.IP "\fBPATH\fR" 4
Used to locate \fIclient\fR and \fBXorg\fR.
.IP "\fBWESTON_LAUNCHER_SOCK" 4
Must be set to "3".
.IP "\fBWESTON_\fR*" 4
Any variable such will be removed from \fIclient\fR's environment.
.IP "\fBDISPLAY\fR" 4
X display number. Will be set to "\fB:\fIN\fR" for \fIclient\fR.
'''
.SH SEE ALSO
\fBxinit\fR(1)
