.TH errno 1
'''
.SH NAME
\fBerrno\fR \- describe error code
'''
.SH SYNOPSYS
errno \fIcode\fR ...
'''
.SH DESCRIPTION
strerror takes either a numeric code like 1 or 22 or a symbolic constant
name like EPERM or EINVAL and output a single-line human-readable error
message like "Operation not permitted" or "Invalid argument".
.P
The tool is meant to be used for Linux system call error codes typically
defined in <errno.h>.
'''
.SH SEE ALSO
\fBstrerror\fR(3), \fBerrno\fR(3), \fBsyscalls\fR(2).
